- name: my play to project 3
  hosts: jos
  become: true
  tasks:
    - name: uupdate repos
      command: apt update
    - name: install docker
      package: name=docker.io state=present
    - name: start docker service
      service: name=docker state=started
    - name: docker image
      command: docker pull luvisjostonj/insurance:2
    - name: docker con
      command: docker run -d -p 8980:8081 luvisjostonj/insurance:2
